### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by andronedev** [nodegui/packer#117]
Cannot find module '@nodegui/nodegui/config/qtConfig'
![image](https://user-images.githubusercontent.com/31452517/94365718-6d7dea00-00d3-11eb-8b26-ee6848764d5c.png)
I've already tried to remove node_modules and reinstall it but nothing works...

**Comment by a7ul** [comment]
Seems like you are using a very old version of @nodegui/nodegui package . Try upgrading it.

**Comment by andronedev** [comment]
I found a solution, it came from my installation of the project, so I used https://react.nodegui.org/docs/guides/getting-started and it works perfectly! Thanks
