### ISSUE TITLE
MacOSX codesign

### ISSUE THREAD

**Issue by MikeHibbert** [nodegui/packer#134]
Hi

I've added code signing as I'd like to distribute my app built with NodeGUI and I've come across and issue where I try to code sign the Application.app folder and I get the following error:

```
stderr: ERROR: Codesign signing error:
ERROR: "/Users/macbookair/Documents/nodejs/evermore-app/deploy/darwin/build/Evermore.app/Contents/MacOS/qode: code object is not signed at all\nIn subcomponent: /Users/macbookair/Documents/nodejs/evermore-app/deploy/darwin/build/Evermore.app/Contents/Frameworks/QtPrintSupport.framework\n"
```

I did this by enabling the packer to send the -codesign=<identity> option so I presume it sends this to the qt deploy program for MacOS?

It also the default install of MiniQT that installs with nodegui too

Any ideas?

**Comment by a7ul** [comment]
Hmm, so the codesign option might not work in all cases.

Instead you try the instructions mentioned  in the readme here:

https://github.com/a7ul/DadJokes

**Comment by MikeHibbert** [comment]
Awesome, I'll work through that one and see how it goes ty!

**Comment by MikeHibbert** [comment]
Thanks ! worked great!
