### ISSUE TITLE
standalone executable on windows?

### ISSUE THREAD

**Issue by danielocdh** [nodegui/packer#154]
I have a working app almost ready but when trying to pack it instead of creating a standalone executable, a folder is created(deploy\win32\build\MyApp) with qode, dist folder and a bunch of .dlls.
The app works when executed like this but if I take the executable to another folder and run it, nothing happens.
I'm just using `npx nodegui-packer --init MyApp` and `npx nodegui-packer --pack ./dist`

Am I missing something?

**Comment by nanohtc** [comment]
You need to grab all files and folders in the MyApp folder too along with the exe.

**Comment by danielocdh** [comment]
> You need to grab all files and folders in MyApp folder too along with the exe.

I had to pause the project for other reasons but if that's as "standalone" as it gets, uff

**Comment by nanohtc** [comment]
You can make a standalone exe by using [https://enigmaprotector.com/en/downloads.html](Enigma Virtual Box). It packs the exe, the dlls, and folders into one exe.

**Comment by danielocdh** [comment]
> You can make a standalone exe by using https://enigmaprotector.com/en/downloads.html. It packs the exe, the dlls, and folders into one exe.
needed it to be completely open source, I'll look into it when/if the project continues, thanks

**Comment by poky1084** [comment]
You may use Node packer npm package but im not sure it it works with NodeGUI apps.
Link: [https://github.com/pmq20/node-packer](https://github.com/pmq20/node-packer)
