### ISSUE TITLE
Packer can not distribute the macOS app

### ISSUE THREAD

**Issue by phuonghuynh** [nodegui/packer#24]
Hi,
I am using packer to deliver my application to another mac machine. After successful running the `packer`, my app can open and run. 
However if I remove my dev `node_modules`, it failed to start without reason/error. If I get back my `node_modules`, it works again. So I guess the issue is about dynamic loading QT framework. How could I fix this? I would like to deliver my app outside my development mac.

**Comment by master-atul** [comment]
Hi @phuonghuynh Are you using webpack to bundle your app? 
because webpack should automatically pack all ur javascript and binaries into a dist folder. And that should basically remove your dependency on node modules. Packer would then copy that dist folder and add qt libraries needed and then pack into a dmg file. 

So my question is have you changed ur setup to something different from what you get via the starter repos?

**Comment by phuonghuynh** [comment]
> So my question is have you changed ur setup to something different from what you get via the starter repos?

@master-atul Nope, clone the starter-repo (react+nodegui) and start developing my application with it. After adding some features, i use `packer` to see how it works, and it working on my dev mac; but no luck on other mac (fresh). I checked this repo, https://soduu.com/rongfengliang/nodegui-react-cal-packer ; and get same issue with mine. Packer can make `cal-app.app` but it can not run on a fresh mac or delete folder `node_modules` (local).
How could i fix this issue? Do you think I could add "nodegui" to `dependency` section (not `devDependency` ?

I attach my `package.json` in case you need to see it.
[package.json.zip](https://github.com/nodegui/packer/files/4012967/package.json.zip)

**Comment by master-atul** [comment]
Hi @phuonghuynh I checked this and it is indeed a bug (not sure when was this introduced). I ll try and get a fix out quickly. Thanks for the details.

**Comment by master-atul** [comment]
Looks like an issue with `node-loader` : https://github.com/webpack-contrib/node-loader/issues/12
I ll probably create a custom webpack loader to fix this.

**Comment by phuonghuynh** [comment]
Thanks for the update @master-atul and Happy new year 🎉

**Comment by master-atul** [comment]
Hi @phuonghuynh 
Please use the following patch for your webpack config to solve the packaging issue

**Comment by phuonghuynh** [comment]
Thanks @master-atul , it fixed
