### ISSUE TITLE
Where does linuxdeployqt.AppImage comes from?

### ISSUE THREAD

**Issue by soonoo** [nodegui/packer#3]
I get below error messages when running `npx nodegui-packer --pack dist` in `nodegui-starter` repo.
```
...
Error: spawn /home/soonoo/dev/nodegui-starter/node_modules/@nodegui/qode/dist/1.0.5/bin/linuxdeployqt.AppImage ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
...
```

I have to manually download `linuxdeployqt` executable from its [repository](https://github.com/probonopd/linuxdeployqt) and copy it to `node_modules/@nodegui/qode/dist/1.0.5/bin/` before packing.  
Is this intended?

System information:  
OS: Arch Linux with kernel version 5.2.14
Node: 12.10.0
npm: 6.11.3

**Comment by slidinghotdog** [comment]
Happens to me too on linux mint, got some errors about permissions, so i think it just doesnt download because of that, solved the same way...

**Comment by master-atul** [comment]
No its not intended :/ . Seems like a bug.

**Comment by probonopd** [comment]
The latest version can always be downloaded from https://github.com/probonopd/linuxdeployqt/releases/tag/continuous.

**Comment by master-atul** [comment]
@probonopd  Thanks for writing linuxdeployqt. It really helped in simplifying packaging process for linux 😄

**Comment by einarpersson** [comment]
I got the following:
```
running linuxdeployqt
Warning: Tried to fix permission for linuxdeployqt but failed
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/einar/Projects/react-nodegui-starter/node_modules/@nodegui/qode/dist/1.0.6/bin/linuxdeployqt.AppImage ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /home/einar/Projects/react-nodegui-starter/node_modules/@nodegui/qode/dist/1.0.6/bin/linuxdeployqt.AppImage',
  path: '/home/einar/Projects/react-nodegui-starter/node_modules/@nodegui/qode/dist/1.0.6/bin/linuxdeployqt.AppImage',
  spawnargs: [
    'qode',
    '-verbose=2',
    '-unsupported-bundle-everything',
    '-appimage',
    '-qmake=/home/einar/Projects/react-nodegui-starter/node_modules/@nodegui/qode/dist/1.0.6/bin/qmake'
  ]
}

```

So what I had to do was to go into `node_modules/@nodegui/qode/dist/1.0.6/bin/` and rename `linuxdeployqt` to `linuxdeployqt.AppImage`. Then it worked.

**Comment by master-atul** [comment]
Thanks for reporting @einarpersson

**Comment by master-atul** [comment]
closing this as packer now downloads it if required automatically
