### ISSUE TITLE
'nodegui-packer@latest' is not in the npm registry?

### ISSUE THREAD

**Issue by disc7** [nodegui/packer#55]
Hi

Am seeing the following error when running `npx nodegui-packer --init MyApp` on my Macbook running High Sierra 10.13.6

`Cs-MacBook-Pro:react-nodegui-packer cabbott$ npx nodegui-packer --init MyApp
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/nodegui-packer - Not found
npm ERR! 404 
npm ERR! 404  'nodegui-packer@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Can see the package is in the npm registry here - https://registry.npmjs.org/@nodegui/packer

Here's the full error log. Thanks for your help.

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'nodegui-packer@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   '/Users/cabbott/.npm/_npx/59738',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose npm-session c73c1d6e7a015d23
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 https://registry.npmjs.org/nodegui-packer 776ms
8 http fetch GET 404 https://registry.npmjs.org/nodegui-packer 665ms
9 silly fetchPackageMetaData error for nodegui-packer@latest 404 Not Found - GET https://registry.npmjs.org/nodegui-packer - Not found
10 timing stage:rollbackFailedOptional Completed in 0ms
11 timing stage:runTopLevelLifecycles Completed in 1460ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/nodegui-packer - Not found
12 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
13 verbose statusCode 404
14 verbose pkgid nodegui-packer@latest
15 verbose cwd /Users/cabbott/Documents/GitRepos/react-nodegui-packer
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "install" "nodegui-packer@latest" "--global" "--prefix" "/Users/cabbott/.npm/_npx/59738" "--loglevel" "error" "--json"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/nodegui-packer - Not found
22 error 404
23 error 404 'nodegui-packer@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
`

**Comment by master-atul** [comment]
Hi @disc7 
I am guessing you forgot to install `@nodegui/packer` first
You need to `npm install --save-dev @nodegui/packer` which would generate `nodegui-packer` binary link 

After this you can do npx nodegui-packer --init

**Comment by master-atul** [comment]
or if you really dont want to install it as dev dependency 
you can do 
`npx --package  @nodegui/packer nodegui-packer  --init`

**Comment by disc7** [comment]
@master-atul, thanks for the quick response. 

Let me confirm my setup. So I've cloned the `React-nodegui-packer` repo and within the seperate `nodegui` project I've setup, need to run:

`npm install --save-dev @nodegui/packer`?

**Comment by master-atul** [comment]
Hey @disc7 what repo is this  `React-nodegui-packer` ?

if you are talking about nodegui/packer you do not need to clone it.

**Comment by disc7** [comment]
Hey 👋

Let me give some more context.

I have nodegui setup - `npm install @nodegui/nodegui`

Have cloned https://github.com/nodegui/nodegui-starter and it's compiling.

Have just run `npm install --save-dev @nodegui/packer without any errors.

Where/ which folder do I run `npx nodegui-packer --init MyApp` ?

**Comment by master-atul** [comment]
now all you need to do is cd to nodegui-starter project
and then `npx nodegui-packer --init MyApp`

**Comment by disc7** [comment]
Getting this error
```Cs-MacBook-Pro:react-nodegui-starter cabbott$ npx nodegui-packer --init MyApp
Cannot find module '@nodegui/nodegui/config/qtConfig'
Require stack:
- /Users/cabbott/Documents/GitRepos/react-nodegui-starter/node_modules/@nodegui/packer/dist/darwin/index.js
- /Users/cabbott/Documents/GitRepos/react-nodegui-starter/node_modules/@nodegui/packer/dist/index.js
- /Users/cabbott/Documents/GitRepos/react-nodegui-starter/node_modules/@nodegui/packer/dist/cli.js```

**Comment by master-atul** [comment]
Seems like you are using an older version of nodegui
Which version are you using ?
Can you update to the latest one ?

**Comment by disc7** [comment]
Installing the latest version of NodeGui fixed it. 

Thanks, @master-atul!
