### ISSUE TITLE
Version 1.4.1 requires macOS 10.15

### ISSUE THREAD

**Issue by lkubaski** [nodegui/packer#64]
Although this is not documented in the release notes, the bundles generated by packer 1.4.1 will fail to run on macOS versions older than 10.15. This is because in the Info.plist file, the LSMinimumSystemVersion key is set to 10.15 (which was not the case with version 1.4.0)

If this is expected, it might be worth explicitely documenting it. 

https://github.com/nodegui/packer/releases/tag/v1.4.1

**Comment by master-atul** [comment]
Hi @lkubaski 
Even though the default info plist template generated by `nodegui-packer --init` command add LSMinimumSystemVersion key to 10.15, you can override it with the version you need. 

`nodegui-packer --pack` will respect your changes and would pack based on it. 
But yeah I think we can set the default LSMinimumSysstemVersion to lower than 10.15 too.

**Comment by master-atul** [comment]
Hi @lkubaski 
Even though the default info plist template generated by `nodegui-packer --init` command add LSMinimumSystemVersion key to 10.15, you can override it with the version you need. 

`nodegui-packer --pack` will respect your changes and would pack based on it. 
But yeah I think we can set the default LSMinimumSysstemVersion to lower than 10.15 too.

**Comment by lkubaski** [comment]
Thanks: I had not realized that it was possible to override the file generated by the --init command. But yeah if this no reason to limit to 10.15 and above it would be great to remove this constaint.
