### ISSUE TITLE
build failing with node react-GUI

### ISSUE THREAD

**Issue by msooraj9452** [nodegui/packer#69]
# i was trying to pack my application for linux but it failed with this error message
{
cleaning build directory at /home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build
creating build directory at /home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build
copying qode
copying dist
running linuxdeployqt
stderr: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'

stderr: Failed to connect to bus: No such file or directory

stderr: Failed to connect to bus: No such file or directory

stdout: Failed to connect to bus: No such file or directory

stdout: Failed to connect to bus: No such file or directory

(node:11841) UnhandledPromiseRejectionWarning: child process exited with code 1
(node:11841) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11841) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
}

**Comment by master-atul** [comment]
Could you try with latest packer 1.4.1 and latest nodegui/react-nodegui versions ? @msooraj9452

**Comment by msooraj9452** [comment]
!# install latest version and it failed at 2nd step
commend --> npx nodegui-packer --init rn-starter
result ->
{
Cannot find module '@nodegui/nodegui/config/qtConfig'
Require stack:
- /home/abhishek/Desktop/JS- Projects/rn-starter/node_modules/@nodegui/packer/dist/linux/index.js
- /home/abhishek/Desktop/JS- Projects/rn-starter/node_modules/@nodegui/packer/dist/index.js
- /home/abhishek/Desktop/JS- Projects/rn-starter/node_modules/@nodegui/packer/dist/cli.js
}

**Comment by master-atul** [comment]
> cannot find `@nodegui/nodegui/config/qtConfig`

This basically means nodegui version is old. Can you confirm that you have updated `@nodegui/nodegui ` package also to latest version ?

**Comment by msooraj9452** [comment]
# i given this a shot. installed latest packages but now step 3 failed
`commend -> npx nodegui-packer --pack ./dist`
`result -> {`
stderr: Unable to guess the architecture of the AppDir source directory "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/rn-starter"
A valid architecture with the ARCH environmental variable should be provided
e.g. ARCH=x86_64 appimagetool ...

stdout: Desktop file: /home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/rn-starter/default.desktop

stderr: Log: ret 256

stderr: Log: WEXITSTATUS(ret) 1

(node:8687) UnhandledPromiseRejectionWarning: child process exited with code 1
(node:8687) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8687) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
}

**Comment by master-atul** [comment]
Can you paste the entire log @msooraj9452 ?

**Comment by msooraj9452** [comment]
# here is the log ===>
stderr: Log: "libicui18n.so.56" already at target location

stderr: Log: Checking rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libicui18n.so.56"

stderr: Log: Changing rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libicui18n.so.56" to "$ORIGIN"

stderr: Log: "libicuuc.so.56" already at target location

stderr: Log: Checking rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libicuuc.so.56"

stderr: Log: Changing rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libicuuc.so.56" to "$ORIGIN"

stderr: Log: "libicudata.so.56" already at target location

stderr: Log: Checking rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libicudata.so.56"

stderr: Log: Changing rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libicudata.so.56" to "$ORIGIN"

stderr: Log: "libGLX.so.0" already at target location

stderr: Log: Checking rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libGLX.so.0"

stderr: Log: Changing rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libGLX.so.0" to "$ORIGIN"

stderr: Log: "libGLdispatch.so.0" already at target location

stderr: Log: Checking rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libGLdispatch.so.0"

stderr: Log: Changing rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libGLdispatch.so.0" to "$ORIGIN"

stderr: Log: "libXau.so.6" already at target location

stderr: Log: Checking rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libXau.so.6"

stderr: Log: Changing rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libXau.so.6" to "$ORIGIN"

stderr: Log: "libXdmcp.so.6" already at target location

stderr: Log: Checking rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libXdmcp.so.6"

stderr: Log: Changing rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libXdmcp.so.6" to "$ORIGIN"

stderr: Log: "libxcb-xkb.so.1" already at target location

stderr: Log: Checking rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libxcb-xkb.so.1"

stderr: Log: Changing rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libxcb-xkb.so.1" to "$ORIGIN"

stderr: Log: "libpcre.so.3" already at target location

stderr: Log: Checking rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libpcre.so.3"

stderr: Log: Changing rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libpcre.so.3" to "$ORIGIN"

stderr: Log: "libsystemd.so.0" already at target location

stderr: Log: Checking rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libsystemd.so.0"

stderr: Log: Changing rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libsystemd.so.0" to "$ORIGIN"

stderr: Log: "libbsd.so.0" already at target location

stderr: Log: Checking rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libbsd.so.0"

stderr: Log: Changing rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libbsd.so.0" to "$ORIGIN"

stderr: Log: "liblzma.so.5" already at target location

stderr: Log: Checking rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/liblzma.so.5"

stderr: Log: Changing rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/liblzma.so.5" to "$ORIGIN"

stderr: Log: "liblz4.so.1" already at target location

stderr: Log: Checking rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/liblz4.so.1"

stderr: Log: Changing rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/liblz4.so.1" to "$ORIGIN"

stderr: Log: "libgcrypt.so.20" already at target location

stderr: Log: Checking rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libgcrypt.so.20"

stderr: Log: Changing rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/lib/libgcrypt.so.20" to "$ORIGIN"

stderr: Log: Checking rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/plugins/xcbglintegrations/libqxcb-glx-integration.so"

stderr: Log: Changing rpath in "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/plugins/xcbglintegrations/libqxcb-glx-integration.so" to "$ORIGIN/../../lib"

stderr: Log: Created configuration file: "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/qt.conf"

stderr: appimagetool, continuous build (commit d185526), build 1855 built on 2018-10-07 20:18:45 UTC

stderr: Name: Application
Icon: default
Exec: AppRun %F
Comment: Edit this default file
Type: Application

stderr: Categories: Utility;

stderr: Unable to guess the architecture of the AppDir source directory "/home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp"
A valid architecture with the ARCH environmental variable should be provided
e.g. ARCH=x86_64 appimagetool ...

stderr: Log: ret 256
Log: WEXITSTATUS(ret) 1

stdout: Desktop file: /home/abhishek/Desktop/JS- Projects/rn-starter/deploy/linux/build/MyApp/default.desktop

(node:3099) UnhandledPromiseRejectionWarning: child process exited with code 1
(node:3099) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3099) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
}

**Comment by master-atul** [comment]
This is super weird but could you try running

`ARCH=x86_64 npx nodegui-packer --pack ./dist`

**Comment by msooraj9452** [comment]
# 2nd option worked!!!.Thanks a lot Atul.

But there one last issue that when i am running this app image it is not creating any shortcut on desktop or in launcher menu. can it be fixed?
