### ISSUE TITLE
packer stuck showing config file.

### ISSUE THREAD

**Issue by TeckFreak** [nodegui/packer#70]
I used the `npx nodegui-packer --init EAT` to initial packer. Then I build the project and then ran the `npx nodegui-packer --pack ./dist` command.
I'm trying to build the Linux executable. Here are the following issues I'm facing:

1. The packer stuck while showing the details of the .desktop file. Here is the screenshot.
![Screenshot from 2020-05-01 10-58-38](https://user-images.githubusercontent.com/25490173/80785512-2cbe8b00-8b9e-11ea-84a5-c88b96918b08.png)
It is stuck here for half and hour.

2. While it is running, I tried running the executables created by double clicking them, they are not running. Below is the screenshot
![Screenshot from 2020-05-01 11-25-14](https://user-images.githubusercontent.com/25490173/80785839-43191680-8b9f-11ea-9a5a-7acba7af75fc.png)

3. I created symlink to .desktop file onto my desktop to run it. Still no luck.

**Comment by TeckFreak** [comment]
@master-atul Kindly help me in this bug.

**Comment by master-atul** [comment]
Hi @TeckFreak Can you try running ./qode from command line and see if that works ?

Looks like linuxdeployqt got stuck while creating appImage. But rest of it went through

**Comment by TeckFreak** [comment]
Yeah, running `./qode` worked, but no AppImage generated. Rest everything went through.
Also, I'd like to mention, I tried building AppImage manually, but the problems it is showing that it requires Ubuntu 14.04 to build and I'm using Ubuntu 20.04.

**Comment by master-atul** [comment]
Yep thats the limitation with latest linuxdeployqt. 
You can try using an older version of linuxdeployqt that works on all versions of ubuntu

**Comment by TeckFreak** [comment]
Okay, I'll try that and get back if it works or not.

**Comment by TeckFreak** [comment]
@master-atul Tried using older versions of linuxdeployqt, same output. Searched in it's issues too, they recommend to build on old machine. Seems the problem is with the software engineering of AppImage.
