### ISSUE TITLE
Duplicate window with process.fork()

### ISSUE THREAD

**Issue by AZn5ReD** [nodegui/packer#71]
Hi,

I don't know if the issue is related to packer or linuxdeployqt, so I try here.

I use node child process `child_process.fork()` in my [program](https://github.com/AZn5ReD/saplearninghub-pdf-downloader-gui/blob/2ace01eaf884b399c3499b490d3599582e1719e8/src/index.ts#L197). I give a file path as input to choose which module to start in the child process. It works fine during npm run debug and npm start, but with the final packer build, it opens a new similar window and closes as soon as the process ends.

Is there a workaround or a fix for that ?

Thank you !

**Comment by constgen** [comment]
Can you try as a workaround `child_process.spawn()`? Because it has an option `{windowsHide: true}`

**Comment by AZn5ReD** [comment]
Works like a charm !
Thanks :+1:
