### ISSUE TITLE
Including Assets (images)

### ISSUE THREAD

**Issue by MadlyFX** [nodegui/packer#93]
What is the correct way to include assets such as images in a Nodegui project, such that Packer can include them in the final packed app?

Obviously referencing an absolute local path won't work, and the method used in the Gif example (const iconImg = require('../assets/icon.png').default, and then   const icon = new QIcon(path.resolve(__dirname, iconImg))) doesn't appear to be working for me, and Packer isn't moving the images to the final build folder.

When Requiring them, the images are added to Dist folder, but renamed such that they can't be resolved anymore.

Just wondering what the correct workflow is here. Thanks!

**Comment by Solant** [comment]
It is handled by a bundler, so packer doesn't need to do anything

You can check how it's done in  https://github.com/nodegui/react-nodegui-starter template with webpack or in https://github.com/nodegui/nodegui-starter , in case you don't use react

**Comment by MadlyFX** [comment]
> 
> 
> It is handled by a bundler, so packer doesn't need to do anything
> 
> You can check how it's done in https://github.com/nodegui/react-nodegui-starter template with webpack or in https://github.com/nodegui/nodegui-starter , in case you don't use react

Thanks, the piece I was missing was to Import the image rather then trying to Require it or use a direct path. Not much documentation using the correct method in this case, but works great.
